[package]
name = "solas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
cgmath = "0.18.0"
random-number = "0.1.7"